version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/spring-boot-ng

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - spring-boot-ng-{{ checksum "pom.xml" }}
          - spring-boot-ng-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-ng-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: server/target/surefire-reports

      - store_artifacts:
          path: client/target/client-0.0.1-SNAPSHOT.jar