version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/spring-boot-ng
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-cache-{{ checksum "pom.xml" }}-{{ checksum "client/package.json" }}
            - m2-cache-
      - run: mvn --fail-never dependency:go-offline
      - save_cache:
          key: m2-cache-{{ checksum "pom.xml" }}-{{ checksum "client/package.json" }}
          paths:
            - ~/.m2
      - run: mvn package
      - store_test_results:
          path: server/target/surefire-reports
      - store_artifacts:
          path: client/target/client-0.0.1-SNAPSHOT.jar